name: notester
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_analytics: ^10.0.7
  equatable: ^2.0.5
  flutter_screenutil: ^5.6.0
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  share_plus: ^6.3.0
  custom_widgets:
    git:
      url: https://github.com/rojanshr1996/custom_widgets.git
      ref: main
  provider: ^6.0.5
  firebase_storage: ^11.0.8
  cached_network_image: ^3.2.3
  file_picker: ^5.2.4
  intl: ^0.17.0
  image_picker: ^0.8.6
  pdf_render: ^1.3.6
  google_sign_in: ^5.4.2
  font_awesome_flutter: ^10.3.0
  like_button: ^2.0.5
  url_launcher: ^6.1.6
  flutter_email_sender: ^5.1.0
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^12.0.4
  flutter_datetime_picker: ^1.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  bloc_test: ^9.1.0
  test: ^1.20.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: euclid
      fonts:
        - asset: fonts/euclidCircularABold.ttf
          weight: 700
        - asset: fonts/euclidCircularASemibold.ttf
          weight: 600
        - asset: fonts/euclidCircularAMedium.ttf
          weight: 500
        - asset: fonts/euclidCircularARegular.ttf
          weight: 400
        - asset: fonts/euclidCircularALight.ttf
          weight: 300

