name: notester
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+8

environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  equatable: ^2.0.7
  path_provider: ^2.1.5
  path: ^1.9.0
  share_plus: ^10.1.4
  custom_widgets:
    git:
      url: https://github.com/rojanshr1996/custom_widgets.git
      ref: main
  provider: ^6.1.5
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  file_picker: ^8.3.7
  intl: ^0.20.2
  image_picker: ^0.8.9
  pdfx: ^2.9.2
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.9.1
  like_button: ^2.1.0
  url_launcher: ^6.3.2
  flutter_email_sender: ^7.0.0
  firebase_messaging: ^15.2.10
  flutter_screenutil: ^5.9.3
  firebase_remote_config: ^5.5.0
  package_info_plus: ^8.3.1
  get_it: ^8.3.0
  firebase_crashlytics: ^4.3.10
  pdf: ^3.11.1
  printing: ^5.13.4
  permission_handler: ^11.3.1
  scribble: ^0.10.0
  image_gallery_saver_plus: ^4.0.1
  screenshot: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/notesterLogo.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^9.1.7
  test: ^1.20.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: euclid
      fonts:
        - asset: fonts/euclidCircularABold.ttf
          weight: 700
        - asset: fonts/euclidCircularASemibold.ttf
          weight: 600
        - asset: fonts/euclidCircularAMedium.ttf
          weight: 500
        - asset: fonts/euclidCircularARegular.ttf
          weight: 400

